### PR TITLE
add 'prefUnmangle' to allow unmangling of text but leaving Safe Link in place

### PR DESCRIPTION
**Pull request by jdpipe**
Hi there
I made some changes to this plugin to suit my own needs, which was that I wanted the formatting of emails to be fixed, while allowing Safe Links to still do their thing. The next step would be to implement a user preferences dialog etc so that this can be edited easily by the end user. Anyway, wanted to pass this along.
Cheers
JP

### CODE REVIEW

**Comment by jdpipe** [comment]
ping @mbattersby, have you seen this PR?

**Comment by mbattersby** [comment]
Hi! Sorry, I missed it. Our org switched away from the safe links stuff a while back and I don't use this plugin myself any more. I'll just merge your PR I have no way of testing it. Scary as it might seem you are probably the primary author now!

**Comment by jdpipe** [comment]
Hey M,
While I’ve got you…
1. What’s the release process?
2. Are you in contact with the original author? The Addons site links to a different page than this project.
Cheers
JP

**Comment by PresGas** [comment]
I just discovered this plugin as well and was confused about who is the primary maintainer. I'm with @jdpipe in wondering...

**Comment by mbattersby** [comment]
I am the original author, I wrote it from scratch in 2016.

**Comment by mbattersby** [comment]
Oops submitted my comment too soon. There's no release process, I don't think I ever bundled it up for any automatic downloads – at least not that I can remember. It sounds like someone else must have packaged it and made it available to an  official list of plugins.

I'm happy to help wrest control back if you need me to, but honestly from my perspective the whole thing is abandonware and as long as you don't take my copyright name out of the code you can do whatever you want within the GPL-3 licensing. I'm happy to delete this repo and just let you use yours if that's helpful.

**Comment by mbattersby** [comment]
Based on https://addons.thunderbird.net/en-us/thunderbird/addon/unmangle-outlook-safelinks/ (which you can see credits me as the original author) it looks like the packager is https://github.com/phavekes/unmangleOutlookSafelinks last updated in 2019. Probably worth talking to them.

**Comment by mbattersby** [comment]
If you look at #1 from 2021 (which I guess I did not really do) phavekes seems to have taken on maintaining my abandonware plugin, including packaging and release (although interestingly their pull request merged their packaging actions into my repo, I assume they aren't working though).

If they are still around, it's probably better if you work with them to continue the maintenance rather than doing it here.

**Comment by PresGas** [comment]
@phavekes was listed as a contributor to this project, so I just `@`-ed them to see about closing this loop. Thanks for filling in some context, @mbattersby !!

**Comment by phavekes** [comment]
Could you make a PR to my fork of this repo, so I can test and release it?

https://github.com/phavekes/unmangleOutlookSafelinks

**Comment by mbattersby** [comment]
I'm not sure it's safe to PR my whole repo against yours. I honestly don't know what state it's in, I've just merged whatever anyone sent. Is there a way to send you this PR somehow?

**Comment by mbattersby** [comment]
I looked at the commits for this PR and they don't apply cleanly to your repo.

So someone would have to redo the PR against your code, hopefully @jdpipe and @phavekes can work together.

**Pull request merged**
